---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |-
    dir /var/lib/redis
    port 6379
    bind 0.0.0.0
    appendonly yes
    daemonize no
    protected-mode no
    requirepass xxxxx
